/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_test_TestParameters */

#ifndef _Included_org_test_TestParameters
#define _Included_org_test_TestParameters
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_test_TestParameters
 * Method:    sumIntegers
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_org_test_TestParameters_sumIntegers
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_test_TestParameters
 * Method:    sayHelloToMe
 * Signature: (Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_test_TestParameters_sayHelloToMe
  (JNIEnv *, jobject, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
