/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_test_impl_Student */

#ifndef _Included_org_test_impl_Student
#define _Included_org_test_impl_Student
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_test_impl_Student
 * Method:    setName
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_test_impl_Student_setName
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_test_impl_Student
 * Method:    setId
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_test_impl_Student_setId
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
