/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_test_TestObjects */

#ifndef _Included_org_test_TestObjects
#define _Included_org_test_TestObjects
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_test_TestObjects
 * Method:    printUserData
 * Signature: (Lorg/test/UserObject;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_test_TestObjects_printUserData
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_test_TestObjects
 * Method:    createUser
 * Signature: (Ljava/lang/String;D)Lorg/test/UserObject;
 */
JNIEXPORT jobject JNICALL Java_org_test_TestObjects_createUser
  (JNIEnv *, jobject, jstring, jdouble);

#ifdef __cplusplus
}
#endif
#endif
